sudo: required
dist: trusty
language: cpp
matrix:
  include:
  - os: linux
    env: TARGET=linux_x86_64
  - os: linux
    env: TARGET=linux_i686
  - os: linux
    env: TARGET=linux_armv7l
  - os: linux
    env: TARGET=linux_aarch64
  - os: linux
    env: TARGET=windows_x86
  - os: linux
    env: TARGET=windows_amd64
  - os: osx
    env: TARGET=darwin
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y -qq; fi
script:
- bash build.sh $TARGET
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then md5 _packages/**/*.tar.gz; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then md5sum _packages/**/*.tar.gz; fi
deploy:
  provider: releases
  api_key:
    secure: EV42P/zhcX5I4huLkQ8SCjtANtvM+w+MZVGj6rIcW35MJaMqcjQg8QWoR3x9Ae6ueKmpbaq4NSzMAkAMvqd6CYNO/Qz/7MpouvbUwu0H1fdvBFA9N1bY2iww9SovnzubpBkPvd7/kmkYC2P0TUCH8IZOBXCnnNQZRiQPKdNDK09rsooo6cbMBNKHMdpPJht+NrRzk43YdOV0gYJd+raaX9E+bQyVe+5GIvIJa1Tdv1CT3jNuAmgZoWV9kfd6eglWE8b+1+p4jbcElaasOTqOMkvq+3FpOplwpEvwwrWspBK44M+TCPc3s8hGDLfJ8QcR18JV2UazlWAYy3p/IiXnyoL24vGJJWs2exTTDEMLnUczK9Mn7ZAXqZ3h0PYu45lSWdFymQjT4/AflJIpvGdzblE8iQCrJfxnzj/53WKWC6CWEG2wKxfIWn0ULAcceDLH1hWK3rFRqpvVRIqSRi+JPVbdiudds5mQGOI8+XYBDHDVTqv2l8rXE3vKZYy/p43JZb+xh+6GiJek3EpDOaOgofasQN2v3XUCjandI/DmZ4V+6CUJTSr+tuWGy/ew79+ZH3/U+JEMSKmVE0dNEzSkvP/1AEENnbi7kH6oGUfddMk02NffRc+x1BhY0VvZSUPAC5WhSCY61UtdGnYGv7wqKUESBhWPUyZOfpXOE/8rhEE=
  file: _packages/**/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: FPGAwars/tools-system
    all_branches: true
